name: DRAGONenv
channels:
  - conda-forge
dependencies:
  - astropy=5.0.*
  - gdal=3.5.*
  - imageio=2.19.*
  - matplotlib=3.5.*
  - netcdf4=1.5.*
  - numpy=1.22.*
  - pandas=1.4.*
  - pyresample=1.23.*
  - pytables=3.7.*
  - python=3.9.*
  - python-geotiepoints=1.4.*
  - pytorch=1.11.*
  - pytorch-lightning=1.5.*
  - scikit-learn=1.1.*
  - seaborn=0.11.*
